#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_demo?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update # Tabele zostaną wygenerowane przez springa
